### PR TITLE
Aosp 9.0.0

### PR DESCRIPTION
**Pull request by rumyantsav**
ok

### CODE REVIEW

**Comment by rahulmsinghvi** [comment]
Are you building lineage os 16 for Nexus 5x?

**Comment by rumyantsav** [comment]
Ok

**Comment by 1ncogn1tus** [comment]
?

**Comment by ThEMarD** [comment]
https://wiki.lineageos.org/submitting-patch-howto.html

**Comment by haggertk** [comment]
Code changes to LineageOS are submitted through Gerrit - https://wiki.lineageos.org/how-to/submitting-patches

**Pull request closed without merging**
